### ISSUE TITLE
Loading different maps in sequence in one play session - Textures not loading correctly

### ISSUE THREAD

**Issue by scaryguy334** [FortressOne/fte-config#14]
Load two maps in sequence in one play session that contain textures with the same file name.
Make sure textures are actually different.

The textures of the first map will be retained, and second map passed over.

Resulting in second map having first maps textures...

vid_reload/vid_restart will fix but not ideal.

alias f_spawn vid_reload
could work? does result in a 'flicker' after map load.

**Comment by drzel** [comment]
Spoike: @zel `r_ignoremapprefixes 0`; `r_keepimages 0` is meant to fix the texture mixup issues. the first cvar is the real fix, but needs the second cvar to avoid memory-(ab)usage problems, but the second cvar may result in weird bugs, which is why they both default to on (when empty).
